spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/app_user
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      platform: mysql

jwt:
  secret: vB4Z$7k*Wq8v^3x&n@Y9Lp#cDf6z!KqRc%3mPrX^b9s?N7jX2$Vg6LqQk2^Mv$w
  expiration: 3600000  # 토큰 유효 기간 (밀리초 단위), 여기서는 1시간


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.web: DEBUG
    com.hell.backend: DEBUG

openai:
  api:
    key: ${OPENAI_API_KEY}

server:
  port: 8081  # 다른 포트 번호로 변경